### ISSUE TITLE
Empties in 3rd class

### ISSUE THREAD

**Issue by michaelnoe** [bgbrink/ddPCRclust#4]
When the programs classifies a samples with only empty droplets, it classifies it in the '3rd marker'-class and not in the 'empties', despite the fluorescent signal being quite low. Off course, visual inspection will intercept this problem, but can this be tackled in an other way?

**Comment by bgbrink** [comment]
Hi @michaelnoe,
Could you send me the file with only empties that is causing trouble, so I can have a look at what's causing the faulty analysis? Thanks a lot!

**Comment by michaelnoe** [comment]
Hi bgBrink,

I’m using multiple files, but it’s happening with this file. I have attached both my file and my template…

Thank you!

Michael

**Comment by bgbrink** [comment]
Hi @michaelnoe 

sorry for late response. I don't see any attachments to your reply. Could you please try again or if it doesn't work, email them directly to bbrink@cebitec.uni-bielefeld.de? Thanks!
