### ISSUE TITLE
Template format example

### ISSUE THREAD

**Issue by todd-testerman** [bgbrink/ddPCRclust#5]
Hello,

Really excited to start using this package for some of our multiplexed ddPCR data. Did have a quick question regarding acceptable template format.

I'm receiving the below error when I try to import my template:
`> template = readTemplate(file_list[9])
Error in readTemplate(file_list[9]) : 
  Invalid Template file! This file starts with:
 ,Well,Samp`

I know that the package comes supplied with a template example but I am unsure how to view this in Excel or some other format where I can model/check my template file against. Would a csv file "template for the template" be able to be provided on this github page? This might be helpful for other users as I felt my file matched what was specified in the vignette but clearly I was wrong. I also attached the template file I am attempting to import (attached as a .txt as github does not support .csv). 
[Combined Probe Experiments.txt](https://github.com/bgbrink/ddPCRclust/files/3026994/Combined.Probe.Experiments.txt)

Thanks again for producing this package and looking forward to working with it!

Todd Testerman

**Comment by bgbrink** [comment]
Hello Todd,
you can find an example template file inside the R package (https://github.com/bgbrink/ddPCRclust/blob/master/inst/extdata/ddPCR_run_template.csv).

Based on your error message, I would assume the header of the file is missing. It should start with ">". 

Let me know if that helps.

**Comment by todd-testerman** [comment]
Yes, that was the problem and the import step worked now. I do have another error that I wouldn't mind running by you when running the ddPCRclust step. I'm happy to post it here or open a new relevant issue if you prefer that (some people want separate posts for each question). 

Thanks!

Todd

**Comment by bgbrink** [comment]
Yes please open a new issue. I will close this one.
