### ISSUE TITLE
Error when using template

### ISSUE THREAD

**Issue by GACGAMA** [bgbrink/ddPCRclust#7]
Hello! I've created my template according to the example, but when I try  

        result <- ddPCRclust(experiment1files , experiment1template)

I get the following error:

Error in `[.data.frame`(template$template, which(template$template[, 1] ==  : 
  undefined columns selected

My R is version 3.6.

My template is as follows:

![image](https://user-images.githubusercontent.com/30120425/67864760-e6ac4000-fb04-11e9-904e-4ac38d9345ee.png)

And my data is as follows:
![image](https://user-images.githubusercontent.com/30120425/67864791-f7f54c80-fb04-11e9-917c-f4ff54cb5313.png)

**Comment by bgbrink** [comment]
Did you use the `readTemplate` function?

**Comment by GACGAMA** [comment]
Yes, with no errors! When I import your example it does work, and it looks like this:

![image](https://user-images.githubusercontent.com/30120425/67865803-b1a0ed00-fb06-11e9-81b3-1184fac78aad.png)


PS: I installed your package with BiocManager::install("ddPCRclust")

**Comment by bgbrink** [comment]
Would you mind sending me the template file you are importing, either here or per mail?
I also noticed the example in the readme on github was outdated, I hope this didn't cause any confusion.

**Comment by GACGAMA** [comment]
This is the template I used!
[experimento 1 template.zip](https://github.com/bgbrink/ddPCRclust/files/3789409/experimento.1.template.zip)

**Comment by bgbrink** [comment]
Ah I see the problem now, disregard my earlier comment. You only provide a template for two Markers, but ddPCRclust always expects four. Just add two more columns, e.g. "Marker3" and "Marker4" and leave them empty if you did not multiplex your samples. I should probably add a check for this so function doesn't just crash with a meaningless error message. Thanks for reporting!

**Comment by GACGAMA** [comment]
Now it works like a charm! Thanks for the very fast response
